<?php
include(ACOC_DRI.'fields/checkbox.php');
include(ACOC_DRI.'fields/heading.php');
include(ACOC_DRI.'fields/image_upload.php');
include(ACOC_DRI.'fields/parallax.php');
include(ACOC_DRI.'fields/post_multi_select.php');
include(ACOC_DRI.'fields/post_select.php');
include(ACOC_DRI.'fields/select.php');
include(ACOC_DRI.'fields/taxonomy_multi_select.php');
include(ACOC_DRI.'fields/taxonomy_select.php');
include(ACOC_DRI.'fields/text.php');
include(ACOC_DRI.'fields/textarea.php');