<?php
add_action( 'admin_init', 'tallykit_slideshow_metabox_register' );
function tallykit_slideshow_metabox_register() {
	
	if(function_exists('ot_register_meta_box')):
		$settings[] = array(
			'id'          => 'tallykit_slideshow_slider_items',
			'label'       => __('Slider Items', 'tallykit_textdomain'),
			'desc'        => '',
			'std'         => '',
			'type'        => 'list-item',
			'section'     => 'branding',
			'rows'        => '',
			'post_type'   => '',
			'taxonomy'    => '',
			'class'       => '',
			'settings'     => array(
				 array(
				 	'id'          => 'type',
					'label'       => __('Type', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'select',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'choices'     => array(
						 array( 'label' => 'Caption Style', 'value' => 'caption' ),
						 array( 'label' => 'Image Only', 'value' => 'image-only' ),
						 array( 'label' => 'Content Only', 'value' => 'content-only' ),
						 array( 'label' => 'Video Only', 'value' => 'video-only' ),
						 array( 'label' => 'Image - Content', 'value' => 'image-content' ),
						 array( 'label' => 'Content - Image', 'value' => 'content-image'),
						 array( 'label' => 'Video - Content', 'value' => 'video-content' ),
						 array( 'label' => 'Content - Video', 'value' => 'content-video'),
					)
				 ),
				 array(
				 	'id'          => 'image',
					'label'       => __('Image', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'upload',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'type:is(image-only),type:is(image-content),type:is(caption),type:is(content-image)',
					'operator'    => 'or'
				 ),
				 array(
				 	'id'          => 'Content',
					'label'       => __('content', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'textarea-simple',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'type:is(caption),type:is(content-only),type:is(image-content),type:is(content-image),type:is(video-content),type:is(content-video)',
					'operator'    => 'or'
				 ),
				  array(
				 	'id'          => 'video',
					'label'       => __('Video oEmbed', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'textarea-simple',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'type:is(video-only),type:is(video-content),type:is(content-video)',
					'operator'    => 'or'
				 ),
				 array(
				 	'id'          => 'active_content_color',
					'label'       => __('Enable Text Color Options', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => 'off',
					'type'        => 'on_off',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
				 ),
				 array(
				 	'id'          => 'heading_color',
					'label'       => __('Heading Color', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'colorpicker',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'active_content_color:is(on)',
					'operator'    => 'or'
				 ),
				 array(
				 	'id'          => 'text_color',
					'label'       => __('Text Color', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'colorpicker',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'active_content_color:is(on)',
					'operator'    => 'or'
				 ),
				 array(
				 	'id'          => 'link_color',
					'label'       => __('Link Color', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'colorpicker',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'active_content_color:is(on)',
					'operator'    => 'or'
				 ),
				 array(
				 	'id'          => 'link_hover_color',
					'label'       => __('Link Hover Color', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'colorpicker',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'active_content_color:is(on)',
					'operator'    => 'or'
				 ),
				 
				 array(
				 	'id'          => 'active_readmore',
					'label'       => __('Enable Readmore', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => 'off',
					'type'        => 'on_off',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
				 ),
				 array(
				 	'id'          => 'readmore_text',
					'label'       => __('Readmore Text', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'text',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'active_readmore:is(on)',
					'operator'    => 'or'
				 ),
				 array(
				 	'id'          => 'readmore_link',
					'label'       => __('Readmore Link', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'text',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'active_readmore:is(on)',
					'operator'    => 'or'
				 ),
				 array(
				 	'id'          => 'readmore_color',
					'label'       => __('Readmore Button Color', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'colorpicker',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'active_readmore:is(on)',
					'operator'    => 'or'
				 ),
				 
				 array(
				 	'id'          => 'active_padding',
					'label'       => __('Enable Padding', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => 'off',
					'type'        => 'on_off',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
				 ),
				 array(
				 	'id'          => 'padding_top',
					'label'       => __('Padding Top', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'text',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'active_padding:is(on)',
					'operator'    => 'or'
				 ),
				 array(
				 	'id'          => 'padding_bottom',
					'label'       => __('Padding Bottom', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'text',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
					'condition'   => 'active_padding:is(on)',
					'operator'    => 'or'
				 ),
				 array(
				 	'id'          => 'content_width',
					'label'       => __('Content Width', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '960px',
					'type'        => 'text',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
				 ),
				 array(
				 	'id'          => 'bg',
					'label'       => __('Background', 'tallykit_textdomain'),
					'desc'        => '',
					'std'         => '',
					'type'        => 'background',
					'section'     => '',
					'rows'        => '',
					'post_type'   => '',
					'taxonomy'    => '',
					'class'       => '',
				 ),
				 
			)
		);
		
		$metabox = array(
			'id'        => 'tallykit_slideshow_metabox',
			'title'     => 'Slider Items',
			'desc'      => '',
			'pages'     => array( 'tallykit_slideshow'),
			'context'   => 'normal',
			'priority'  => 'high',
			'fields'    => $settings,
		);
		ot_register_meta_box( $metabox );
	endif;
}